version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn workspace visits-style test:ci
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn workspace visits-style build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/packages/visits-style/dist/.npmrc
      - run: cd ~/repo/packages/visits-style/dist && npm publish
      - persist_to_workspace:
          root: ~/repo
          paths: .
  doc:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: deploy
          command: yarn workspace visits-style-website deploy
  storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: deploy
          command: yarn workspace visits-style storybook:deploy

workflows:
  version: 2
  publish:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - checkout_code
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      # - doc:
      #     requires:
      #       - deploy
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
      # - storybook:
      #     requires:
      #       - doc
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/