declare const _default: {
    fontFamily: string;
    fontSize: string;
    responsive: boolean;
    primary: string;
    link: string;
    info: string;
    success: string;
    warning: string;
    danger: string;
    dark: string;
    light: string;
    black: string;
    blackBis: string;
    blackTer: string;
    white: string;
    whiteBis: string;
    whiteTer: string;
    grey: string;
    greyLight: string;
    greyLighter: string;
    text: string;
    textDark: string;
    textLight: string;
    textStrong: string;
    background: string;
    border: string;
    borderHover: string;
    borderActive: string;
};
export default _default;
