"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    fontFamily: '"Hiragino Sans", ヒラギノ角ゴシック, "Hiragino Kaku Gothic ProN", "ヒラギノ角ゴ ProN W3", 游ゴシック体, "Yu Gothic", YuGothic, "ヒラギノ角ゴシック Pro", HiraKakuPro-W3, "Hiragino Kaku Gothic Pro", Quicksand, メイリオ, Meiryo, Osaka, "ＭＳ Ｐゴシック", "MS PGothic", sans-serif',
    fontSize: '16px',
    responsive: true,
    primary: '#37B151',
    link: '#578ba9',
    info: '#209cee',
    success: '#0fa886',
    warning: '#f2b541',
    danger: '#f3575a',
    dark: '#363636',
    light: '#9b9b9b',
    black: '#0a0a0a',
    blackBis: '#121212',
    blackTer: '#242424',
    white: '#ffffff',
    whiteBis: '#fafafa',
    whiteTer: '#f5f5f5',
    grey: '#7a7a7a',
    greyLight: '#9b9b9b',
    greyLighter: '#dbdbdb',
    text: '#4a4a4a',
    textDark: '#4a4a4a',
    textLight: '#7a7a7a',
    textStrong: '#4a4a4a',
    background: '#f5f5f5',
    border: '#dbdbdb',
    borderHover: '#9b9b9b',
    borderActive: '#4a4a4a',
};
