"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.red = exports.purple = exports.blue = exports.cyan = exports.turquoise = exports.green = exports.yellow = exports.orange = exports.white = exports.whiteBis = exports.whiteTer = exports.greyLighter = exports.greyLight = exports.grey = exports.greyDark = exports.greyDarker = exports.blackTer = exports.blackBis = exports.black = void 0;
var black = '#0a0a0a';
exports.black = black;
var blackBis = '#121212';
exports.blackBis = blackBis;
var blackTer = '#242424';
exports.blackTer = blackTer;
var greyDarker = '#363636';
exports.greyDarker = greyDarker;
var greyDark = '#4a4a4a';
exports.greyDark = greyDark;
var grey = '#7a7a7a';
exports.grey = grey;
var greyLight = '#9b9b9b';
exports.greyLight = greyLight;
var greyLighter = '#dbdbdb';
exports.greyLighter = greyLighter;
var whiteTer = '#f5f5f5';
exports.whiteTer = whiteTer;
var whiteBis = '#fafafa';
exports.whiteBis = whiteBis;
var white = '#ffffff';
exports.white = white;
var orange = '#ff460f';
exports.orange = orange;
var yellow = '#f2b541';
exports.yellow = yellow;
var green = '#0fa886';
exports.green = green;
var turquoise = '#37B151';
exports.turquoise = turquoise;
var cyan = '#209cee';
exports.cyan = cyan;
var blue = '#578ba9';
exports.blue = blue;
var purple = '#b86bff';
exports.purple = purple;
var red = '#f3575a';
exports.red = red;