name: publish and deploy
on:
  push:
    tags:
      - v*
jobs:
  test:
    name: run lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn workspace visits-style lint
      - run: yarn workspace visits-style test:ci
  publish:
    name: publish to npm
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn workspace visits-style build
      - run: cp ./LICENSE ./packages/core
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > ./packages/core/.npmrc
      - run: cd ./packages/core && npm publish
  # document:
  #   name: update document
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '10.x'
  #     - run: yarn install
  #     - run: yarn workspace visits-style-website deploy
  #     - run: yarn workspace visits-style storybook:deploy
