name: publish and deploy
on:
  push:
    tags:
      - v*
jobs:
  test:
    name: run lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', 'latest' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test:ci
  publish:
    name: publish to npm
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > .npmrc
      - run: npm publish
  document:
    name: update document
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn storybook:deploy
