name: publish and deploy
on:
  push:
    tags:
      - v*
jobs:
  test:
    name: run lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', 'latest' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn workspace visits-style lint
      - run: yarn workspace visits-style test:ci
  publish:
    name: publish to npm
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn workspace visits-style build
      - run: cp ./LICENSE ./packages/core
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > ./packages/core/.npmrc
      - run: cd ./packages/core && npm publish
  document:
    name: update document
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn workspace visits-style storybook:deploy
