name: Run test for pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: run lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', 'latest' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-yarn-
      - run: yarn install
      - run: yarn lint
      - run: yarn test:ci
